nilemart/routes/web.php
        Route::namespace('Drivers')->group(function () {
            // Route::resource('driver', 'DriverController');
            Route::get('driver/index', 'DriverController@show')->name('driver.index');
            Route::get('driver/usershow/{id}', 'DriverController@usershow')->name('driver.usershow');
            Route::get('driver/create/', 'DriverController@create')->name('driver.create');
            Route::post('driver/store', 'DriverController@store')->name('driver.store');
            Route::get('driver/edit/{id}', 'DriverController@edit')->name('driver.edit');
            Route::get('driver/destroy/{id}', 'DriverController@destroy')->name('driver.destroy');
        });

        //Payment
        Route::namespace('Payments')->group(function () {
            Route::resource('payment', 'PaymentController');
            Route::get('payment/driver/{id}/total/{total}', 'PaymentController@driverNotification');
            Route::get('payment/drivers/payment/otp', 'PaymentController@driverNotifications')->name('driver.payment.otp');
            Route::post('payment/drivers/payment', 'PaymentController@paymentSubmit')->name('driver.payment');
        });

        Route::resource('addresses', 'Addresses\AddressController');
        Route::resource('countries', 'Countries\CountryController');
        Route::resource('countries.provinces', 'Provinces\ProvinceController');
        Route::resource('countries.provinces.cities', 'Cities\CityController');
        Route::resource('couriers', 'Couriers\CourierController');
        Route::resource('attributes', 'Attributes\AttributeController');
        Route::resource('attributes.values', 'Attributes\AttributeValueController');
        Route::resource('brands', 'Brands\BrandController');

        Route::get('list-customer', 'Wallet\WalletController@index')->name('wallet.index');
        Route::get('wallet-show/{id}', 'Wallet\WalletController@walletSummery')->name('wallet.show');

        // });
        //Changed the employees to companies
        // Route::group(['middleware' => ['role:admin|superadmin, guard:employee']], function () {
        Route::resource('companies', 'CompaniesController');
        Route::get('companies/{id}/profile', 'CompaniesController@getProfile')->name('companies.profile');
        Route::get('remove-logo', 'CompaniesController@removeLogo')->name('company.remove.logo');
        Route::get('changeStatus', 'CompaniesController@changeStatus')->name('companies.status');
        Route::put('companies/{id}/profile', 'CompaniesController@updateProfile')->name('companies.profile.update');
        Route::resource('roles', 'Roles\RoleController');
        Route::resource('permissions', 'Permissions\PermissionController');
 
        Route::get('cms/tearm_condtion/index','CMS\TearmCondtionController@index')->name('cms.tearm_condtion.index');
        Route::post('cms/tearm_condtion/update', 'CMS\TearmCondtionController@update')->name('cms.tearm_condtion.update');

        Route::get('cms/privacy_policy/index','CMS\PrivacyPolicyController@index')->name('cms.privacy_policy.index');
        Route::post('cms/privacy_policy/update', 'CMS\PrivacyPolicyController@update')->name('cms.privacy_policy.update');
        // });

        //Faq
        Route::get('faq/index', 'Faq\FaqController@index')->name('faq.index');
        Route::get('faq/create/', 'Faq\FaqController@create')->name('faq.create');
        Route::post('faq/store', 'Faq\FaqController@store')->name('faq.store');
        Route::get('faq/edit/{id}', 'Faq\FaqController@edit')->name('faq.edit');
        Route::get('faq/destroy/{id}', 'Faq\FaqController@destroy')->name('faq.destroy');
        // });


        Route::namespace('Orderpurchase')->group(function () {
            Route::resource('orderpurchase', 'OrderpurchaseController');
            Route::post('removeProductattribute','OrderpurchaseController@removeProductattribute')->name('orderpurchase.removeProductattribute');
            Route::get('getProducts', 'OrderpurchaseController@getProducts')->name('orderpurchase.getProducts');
            Route::post('getProductsattribute', 'OrderpurchaseController@getProductsattribute')->name('orderpurchase.getProductsattribute');
            Route::post('getProductsdetail', 'OrderpurchaseController@getProductsdetail')->name('orderpurchase.getProductsdetail');
            Route::post('orderpurchase/update/{id}', 'OrderpurchaseController@update')->name('orderpurchase.update');
            Route::get('orderpurchase/{id}/invoice', 'OrderpurchaseController@generateInvoice')->name('orderpurchase.invoice.generate');
        });
    });
    Route::get('translate', 'Admin\TranslateController@translate')->name('translate');
});

/**
 * Frontend routes
 */
Auth::routes();
Route::namespace('Auth')->group(function () {
    Route::get('cart/login', 'CartLoginController@showLoginForm')->name('cart.login');
    Route::post('cart/login', 'CartLoginController@login')->name('cart.login');
    Route::get('logout', 'LoginController@destroy');
    Route::get('user/login', 'LoginController@loginform')->name('userLogin');
    Route::post('/user/login', 'LoginController@loginstore')->name('loginstore');
    Route::post('/user/register/login', 'LoginController@registerloginstore')->name('registerloginstore');
    Route::post('/register/{no}', 'LoginController@register')->name('userRegistration');
    Route::post('register', 'LoginController@store')->name('userStorRegistration');
    Route::post('resendotp', 'LoginController@resendOtp')->name('resendotp');

});

Route::namespace('Front')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::group(['middleware' => ['auth', 'web']], function () {

        Route::namespace('Payments')->group(function () {
            Route::get('bank-transfer', 'BankTransferController@index')->name('bank-transfer.index');
            Route::post('bank-transfer', 'BankTransferController@store')->name('bank-transfer.store');
        });

        Route::namespace('Addresses')->group(function () {
            Route::resource('country.state', 'CountryStateController');
            Route::resource('state.city', 'StateCityController');
        });

        Route::get('accounts', 'AccountsController@index')->name('accounts');
        Route::get('checkout', 'CheckoutController@index')->name('checkout.index');
        Route::post('checkout', 'CheckoutController@store')->name('checkout.store');
        Route::get('checkout/execute', 'CheckoutController@executePayPalPayment')->name('checkout.execute');
        Route::post('checkout/execute', 'CheckoutController@charge')->name('checkout.execute');
        Route::get('checkout/cancel', 'CheckoutController@cancel')->name('checkout.cancel');
        Route::get('checkout/success', 'CheckoutController@success')->name('checkout.success');
        Route::resource('customer.address', 'CustomerAddressController');
    });
    Route::resource('cart', 'CartController');
    Route::get("category/{slug}", 'CategoryController@getCategory')->name('front.category.slug');
    // Route::get("search", 'ProductController@search')->name('search.product');
    // Route::get("{product}", 'ProductController@show')->name('front.get.product');

    Route::get("productCategory", 'ProductController@productCategory')->name('productCategory.product');
    Route::get("productSubCategory/{id}", 'ProductController@productSubCategory')->name('productSubCategory.product');
    Route::get("productDetail/{id}", 'ProductController@productDetail')->name('productDetail.product');
    Route::get("productListing", 'ProductController@productListing')->name('productListing.product');
    Route::get("product/{id}", 'ProductController@productCategoryListing')->name('productCategoryListing.product');
    Route::get("productCategory/{cat}", 'ProductController@productCategoryListingCat')->name('productCategoryListingCat.product');
    Route::get("productSubSubCategory/{id}", 'ProductController@productSubSubCategory')->name('productSubSubCategory.name');
    
    Route::get("checkout", 'ProductController@checkout')->name('checkout.product');
    //Route::get("productDetail/productCheckcart", 'ProductController@productCheckcart')->name('productDetail.productCheckcart');
    Route::get("myorder", 'ProductController@myorder')->name('myorder');

    Route::get("profile",'ProfileController@profile')->name('profile');
    Route::get("contact-us",'ProfileController@contactus')->name('contactus');
    Route::post("send-email",'ProfileController@sendEmail');
    Route::get("tearm-condition",'ProfileController@tearmcondition')->name('tearmcondition');
    Route::get("privacy-policy",'ProfileController@privacypolicy')->name('privacypolicy');
    Route::get("faq",'ProfileController@faq')->name('faq');
    Route::get("customer/orderhistory",'ProfileController@orders')->name('orders');
    Route::get("customer/orderhistory/{id}",'ProfileController@show')->name('show');
    Route::get("about-us",'ProfileController@aboutus')->name('aboutus');
    Route::post("editProfile/{id}",'ProfileController@editProfile')->name('editProfile');
    Route::post("editAddress/{id}",'ProfileController@editAddress')->name('editAddress');
    Route::get("productCheckcart", 'HomeController@productCheckcart')->name('productCheckcart');
    Route::get("SelectUnitPrice/{id}", 'HomeController@SelectUnitPrice')->name('SelectUnitPrice');
    Route::post("getProductSearch", 'ProductController@getProductSearch')->name('getProductSearch');
    Route::post("updatecart", 'ProductController@updatecart')->name('updatecart');
    Route::get("SelectUnitPrice/{id}", 'HomeController@SelectUnitPrice')->name('SelectUnitPrice');
    
    Route::get("defaultAddres", 'ProductController@defaultAddres')->name('defaultAddres');
    Route::get("DeleteCart", 'ProductController@deleteCart')->name('DeleteCart');
    
    Route::post("contact/mails", 'ContactController@mailsend')->name('contact.mails');

nilemart/app/Http/Controllers/Front/AccountsController.php
<?php

namespace App\Http\Controllers\Front;

use App\Shop\Couriers\Repositories\Interfaces\CourierRepositoryInterface;
use App\Shop\Customers\Repositories\CustomerRepository;
use App\Shop\Customers\Repositories\Interfaces\CustomerRepositoryInterface;
use App\Http\Controllers\Controller;
use App\Shop\Orders\Order;
use App\Shop\Orders\Transformers\OrderTransformable;

class AccountsController extends Controller
{
    use OrderTransformable;

    /**
     * @var CustomerRepositoryInterface
     */
    private $customerRepo;

    /**
     * @var CourierRepositoryInterface
     */
    private $courierRepo;

    /**
     * AccountsController constructor.
     *
     * @param CourierRepositoryInterface $courierRepository
     * @param CustomerRepositoryInterface $customerRepository
     */
    public function __construct(
        CourierRepositoryInterface $courierRepository,
        CustomerRepositoryInterface $customerRepository
    ) {
        $this->customerRepo = $customerRepository;
        $this->courierRepo = $courierRepository;
    }

    public function index()
    {
        $customer = $this->customerRepo->findCustomerById(auth()->user()->id);

        $customerRepo = new CustomerRepository($customer);
        $orders = $customerRepo->findOrders(['*'], 'created_at');

        $orders->transform(function (Order $order) {
            return $this->transformOrder($order);
        });

        $addresses = $customerRepo->findAddresses();

        return view('front.accounts', [
            'customer' => $customer,
            'orders' => $this->customerRepo->paginateArrayResults($orders->toArray(), 15),
            'addresses' => $addresses
        ]);
    }

    
}

nilemart/app/Http/Controllers/Front/Addresses/CountryStateController.php
<?php

namespace App\Http\Controllers\Front\Addresses;

use App\Http\Controllers\Controller;
use App\Shop\Countries\Repositories\CountryRepository;
use App\Shop\Countries\Repositories\Interfaces\CountryRepositoryInterface;

class CountryStateController extends Controller
{
    private $countryRepo;

    /**
     * CountryStateController constructor.
     *
     * @param CountryRepositoryInterface $countryRepository
     */
    public function __construct(CountryRepositoryInterface $countryRepository)
    {
        $this->countryRepo = $countryRepository;
    }

    /**
     * @param $countryId
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function index($countryId)
    {
        $country = $this->countryRepo->findCountryById($countryId);

        $countryRepo = new CountryRepository($country);
        $data = $countryRepo->listStates();

        return response()->json(compact('data'));
    }
}

nilemart/app/Http/Controllers/Front/Addresses/StateCityController.php
<?php

namespace App\Http\Controllers\Front\Addresses;

use App\Http\Controllers\Controller;
use App\Shop\States\Repositories\StateRepository;
use App\Shop\States\Repositories\StateRepositoryInterface;

class StateCityController extends Controller
{
    private $stateRepo;

    /**
     * StateCityController constructor.
     *
     * @param StateRepositoryInterface $stateRepository
     */
    public function __construct(StateRepositoryInterface $stateRepository)
    {
        $this->stateRepo = $stateRepository;
    }

    /**
     * @param $state_code
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function index($state_code)
    {
        $state = $this->stateRepo->findOneBy(compact('state_code'));

        $stateRepo = new StateRepository($state);
        $data = $stateRepo->listCities();

        return response()->json(compact('data'));
    }
}

nilemart/app/Http/Controllers/Front/CategoryController.php
<?php

namespace App\Http\Controllers\Front;

use App\Shop\Categories\Repositories\CategoryRepository;
use App\Shop\Categories\Repositories\Interfaces\CategoryRepositoryInterface;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    /**
     * @var CategoryRepositoryInterface
     */
    private $categoryRepo;

    /**
     * CategoryController constructor.
     *
     * @param CategoryRepositoryInterface $categoryRepository
     */
    public function __construct(CategoryRepositoryInterface $categoryRepository)
    {
        $this->categoryRepo = $categoryRepository;
    }

    /**
     * Find the category via the slug
     *
     * @param string $slug
     * @return \App\Shop\Categories\Category
     */
    public function getCategory(string $slug)
    {
        $category = $this->categoryRepo->findCategoryBySlug(['slug' => $slug]);

        $repo = new CategoryRepository($category);

        $products = $repo->findProducts()->where('status', 1)->all();

        return view('front.categories.category', [
            'category' => $category,
            'products' => $repo->paginateArrayResults($products, 20)
        ]);
    }
}

nilemart/app/Http/Controllers/Front/ContactController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use App\Shop\Addresses\Requests\CreateAddressRequest;
use App\Shop\Addresses\Requests\UpdateAddressRequest;
use App\Shop\Addresses\Repositories\AddressRepository;
use App\Shop\Cities\Repositories\Interfaces\CityRepositoryInterface;
use App\Shop\Addresses\Repositories\Interfaces\AddressRepositoryInterface;
use App\Shop\Countries\Repositories\Interfaces\CountryRepositoryInterface;
use App\Shop\Provinces\Repositories\Interfaces\ProvinceRepositoryInterface;
use Illuminate\Http\Request;
use App\Helper\MailHelper;

class ContactController extends Controller
{
    /**
     * @var AddressRepositoryInterface
     */
    private $addressRepo;

    /**
     * @var CountryRepositoryInterface
     */
    private $countryRepo;

    /**
     * @var CityRepositoryInterface
     */
    private $cityRepo;

    /**
     * @var ProvinceRepositoryInterface
     */
    private $provinceRepo;


    /**
     * @param AddressRepositoryInterface  $addressRepository 
     * @param CountryRepositoryInterface  $countryRepository 
     * @param CityRepositoryInterface     $cityRepository    
     * @param ProvinceRepositoryInterface $provinceRepository
     */
    public function __construct(
        AddressRepositoryInterface $addressRepository,
        CountryRepositoryInterface $countryRepository,
        CityRepositoryInterface $cityRepository,
        ProvinceRepositoryInterface $provinceRepository
    ) {
        $this->addressRepo = $addressRepository;
        $this->countryRepo = $countryRepository;
        $this->provinceRepo = $provinceRepository;
        $this->cityRepo = $cityRepository;
    }

    /**
     * @param CreateAddressRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function mailSend(Request $request)
    {
        $data = [
            'email'   => $request->input('email')
        ];
//        dd($request->all());
        $customer_mail = MailHelper::sendMailCustomer($data);
        
        return redirect()->back()->with('success', 'Mail Has been sent!');
    }
}

nilemart/resources/views/front/carts/cart.blade.php
@extends('layouts.front.app')

@section('content')
        <div class="container product-in-cart-list">
            @if(!$cartItems->isEmpty())
                <div class="row">
                    <div class="col-md-12">
                        <ol class="breadcrumb">
                            <li><a href="{{ route('home') }}"> <i class="fa fa-home"></i> Home</a></li>
                            <li class="active">Cart</li>
                        </ol>
                    </div>
                    <div class="col-md-12 content">
                        <div class="box-body">
                            @include('layouts.errors-and-messages')
                        </div>
                        <h3><i class="fa fa-cart-plus"></i> Shopping Cart</h3>
                        <table class="table table-striped">
                            <thead>
                                <th class="col-md-2 col-lg-2">Cover</th>
                                <th class="col-md-2 col-lg-5">Name</th>
                                <th class="col-md-2 col-lg-2">Quantity</th>
                                <th class="col-md-2 col-lg-1"></th>
                                <th class="col-md-2 col-lg-2">Price</th>
                            </thead>
                            <tfoot>
                            <tr>
                                <td class="bg-warning">Subtotal</td>
                                <td class="bg-warning"></td>
                                <td class="bg-warning"></td>
                                <td class="bg-warning"></td>
                                <td class="bg-warning">{{config('cart.currency')}} {{ number_format($subtotal, 2, '.', ',') }}</td>
                            </tr>
                            @if(isset($shippingFee) && $shippingFee != 0)
                            <tr>
                                <td class="bg-warning">Shipping</td>
                                <td class="bg-warning"></td>
                                <td class="bg-warning"></td>
                                <td class="bg-warning"></td>
                                <td class="bg-warning">{{config('cart.currency')}} {{ $shippingFee }}</td>
                            </tr>
                            @endif
                            <tr>
                                <td class="bg-warning">Tax</td>
                                <td class="bg-warning"></td>
                                <td class="bg-warning"></td>
                                <td class="bg-warning"></td>
                                <td class="bg-warning">{{config('cart.currency')}} {{ number_format($tax, 2) }}</td>
                            </tr>
                            <tr>
                                <td class="bg-success">Total</td>
                                <td class="bg-success"></td>
                                <td class="bg-success"></td>
                                <td class="bg-success"></td>
                                <td class="bg-success">{{config('cart.currency')}} {{ number_format($total, 2, '.', ',') }}</td>
                            </tr>
                            </tfoot>
                            <tbody>
                            @foreach($cartItems as $cartItem)
                                <tr>
                                    <td>
                                        <a href="{{ route('front.get.product', [$cartItem->product->slug]) }}" class="hover-border">
                                            @if(isset($cartItem->cover))
                                                <img src="{{$cartItem->cover}}" alt="{{ $cartItem->name }}" class="img-responsive img-thumbnail">
                                            @else
                                                <img src="https://placehold.it/120x120" alt="" class="img-responsive img-thumbnail">
                                            @endif
                                        </a>
                                    </td>
                                    <td>
                                        <h3>{{ $cartItem->name }}</h3>
                                        @if($cartItem->options->has('combination'))
                                            @foreach($cartItem->options->combination as $option)
                                                <small class="label label-primary">{{$option['value']}}</small>
                                            @endforeach
                                        @endif
                                        <div class="product-description">
                                            {!! $cartItem->product->description !!}
                                        </div>
                                    </td>
                                    <td>
                                        <form action="{{ route('cart.update', $cartItem->rowId) }}" class="form-inline" method="post">
                                            {{ csrf_field() }}
                                            <input type="hidden" name="_method" value="put">
                                            <div class="input-group">
                                                <input type="text" name="quantity" value="{{ $cartItem->qty }}" class="form-control" />
                                                <span class="input-group-btn"><button class="btn btn-default">Update</button></span>
                                            </div>
                                        </form>
                                    </td>
                                    <td>
                                        <form action="{{ route('cart.destroy', $cartItem->rowId) }}" method="post">
                                            {{ csrf_field() }}
                                            <input type="hidden" name="_method" value="delete">
                                            <button onclick="return confirm('Are you sure?')" class="btn btn-danger"><i class="fa fa-times"></i></button>
                                        </form>
                                    </td>
                                    <td>{{config('cart.currency')}} {{ number_format($cartItem->price, 2) }}</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        <hr>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="btn-group pull-right">
                                    <a href="{{ route('home') }}" class="btn btn-default">Continue shopping</a>
                                    <a href="{{ route('checkout.index') }}" class="btn btn-primary">Go to checkout</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            @else
                <div class="row">
                    <div class="col-md-12">
                        <p class="alert alert-warning">No products in cart yet. <a href="{{ route('home') }}">Shop now!</a></p>
                    </div>
                </div>
            @endif
        </div>
@endsection
@section('css')
    <style type="text/css">
        .product-description {
            padding: 10px 0;
        }
        .product-description p {
            line-height: 18px;
            font-size: 14px;
        }
    </style>
@endsection

nilemart/resources/views/front/carts/login.blade.php
@extends('layouts.front.app')

@section('content')
    <hr>
    <!-- Main content -->
    <section class="container content">
        <div class="row">
            <div class="col-md-12">@include('layouts.errors-and-messages')</div>
            <div class="col-md-5">
                <h2>Login to your account</h2>
                <form action="{{ route('cart.login') }}" method="post" class="form-horizontal">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label for="email" class="control-label">Email</label>
                        <input type="email" id="email" name="email" value="{{ old('email') }}" class="form-control" placeholder="Email" autofocus>
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" name="password" id="password" value="" class="form-control" placeholder="xxxxx">
                    </div>
                    <div class="row">
                        <button class="btn btn-primary btn-block" type="submit">Login now</button>
                    </div>
                </form>
                <div class="row"><hr>
                    <a href="#">I forgot my password</a><br>
                </div>
            </div>
            <div class="col-md-6 col-md-offset-1">
                <h2>Register an account</h2>
                <form class="form-horizontal" method="POST" action="{{ route('register') }}">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label for="name" class="control-label">Name</label>
                        <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required>
                    </div>

                    <div class="form-group">
                        <label for="email" class="control-label">E-Mail Address</label>
                        <input id="email" type="email" class="form-control" name="email" value="{{ old('email') }}" required>
                    </div>

                    <div class="form-group">
                        <label for="password" class="control-label">Password</label>
                        <input id="password" type="password" class="form-control" name="password" required>
                    </div>

                    <div class="form-group">
                        <label for="password-confirm" class="control-label">Confirm Password</label>
                        <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block">Register</button>
                    </div>
                </form>
            </div>
        </div>
    </section>
    <!-- /.content -->
@endsection