nilemart/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/**
 * Admin routes
 */
Route::namespace('Admin')->group(function () {
    Route::get('admin/login', 'LoginController@showLoginForm')->name('admin.login');
    Route::post('admin/login', 'LoginController@login')->name('admin.login');
    Route::get('admin/logout', 'LoginController@logout')->name('admin.logout');
});
Route::group(['prefix' => 'admin', 'middleware' => ['employee'], 'as' => 'admin.'], function () {
    Route::namespace('Admin')->group(function () {
        // Route::group(['middleware' => ['role:admin|superadmin|clerk, guard:employee']], function () {
        Route::get('/', 'DashboardController@index')->name('dashboard');
        Route::namespace('Products')->group(function () {
            Route::resource('products', 'ProductController');
            Route::get('remove-image-product', 'ProductController@removeImage')->name('product.remove.image');
            Route::get('remove-image-thumb', 'ProductController@removeThumbnail')->name('product.remove.thumb');
            Route::post('getCategories', 'ProductController@getCategories')->name('products.getCategories');
            Route::post('getSubSubCategories', 'ProductController@getSubSubCategories')->name('products.getSubSubCategories');
            Route::post('removeProductProduct', 'ProductController@removeProductattribute')->name('products.removeProductProduct');
            Route::post('getCropCategories', 'ProductController@getCropCategories')->name('products.getCropCategories');
            Route::post('getSubCategories', 'ProductController@getSubCategories')->name('products.getSubCategories');
            Route::get('checkhsncode', 'ProductController@checkHsnCode')->name('products.checkhsncode');
        });
        Route::namespace('Customers')->group(function () {
            Route::resource('customers', 'CustomerController');
            Route::resource('customers.addresses', 'CustomerAddressController');
        });
        // Route::namespace('Crop')->group(function () {
        //     Route::resource('crops', 'CropController');
        // });
        Route::namespace('Crops')->group(function () {
            Route::resource('crops', 'CropController');
            Route::get('crops/create/{id?}', 'CropController@create')->name('crops.create');
        });

        Route::namespace('CustomerNotifications')->group(function () {
            Route::post('getValue', 'NotificationController@getValue')->name('notifications.getValue');
            Route::resource('notifications', 'NotificationController');
        });

        Route::namespace('TechnicalCategoties')->group(function () {
            Route::resource('technical', 'TechnicalController');
        });

        Route::namespace('UpdateStocks')->group(function () {
            Route::resource('updateStock', 'UpdateStockController');
        });


        Route::namespace('Postcodes')->group(function () {
            Route::resource('postcode', 'PostcodeController');
        });

        Route::namespace('CountriesData')->group(function () {
            Route::resource('country_data', 'CountryDataController');
            Route::get('country_data/show-tehsil/{id?}', 'CountryDataController@showTehsil')->name('country_data.showTehsil');
            Route::get('country_data/show-village/{id?}', 'CountryDataController@showVillage')->name('country_data.showVillage');
            Route::get('country_data/destroy-village/{id?}', 'CountryDataController@destroyVillage')->name('country_data.destroyVillage');
            Route::post('getCity', 'CountryDataController@getCity')->name('country_data.getCity');
            Route::post('getTehsil', 'CountryDataController@getTehsil')->name('country_data.getTehsil');
            Route::get('createVillage', 'CountryDataController@createVillage')->name('country_data.createVillage');
            Route::get('createCity', 'CountryDataController@createCity')->name('country_data.createCity');
        });

        Route::namespace('Priorities')->group(function () {
            Route::resource('pro_priority', 'PriorityController');
            // Route::post('update', 'PriorityController@update');
            Route::post('pro_priority/sort', 'PriorityController@cat_sort')->name('priority.sort');
            Route::post('pro_priority/subcat_sort', 'PriorityController@subcat_sort')->name('priority.subcat_sort');
            Route::post('pro_priority/getProduct', 'PriorityController@getProduct')->name('priority.getProduct');
            Route::post('pro_priority/getCategoryProduct', 'PriorityController@getCategoryProduct')->name('priority.getCategoryProduct');
        });

        Route::namespace('Offers')->group(function () {
            Route::resource('offers', 'OffersController');
            Route::get('offers_product', 'OffersController@getProduct')->name('offers.product.attr');
            Route::post('offers/{id}', 'OffersController@update')->name('offers.update');
            Route::get('remove-image-offer', 'OffersController@removeImage')->name('offers.remove.image');
        });
        Route::namespace('Categories')->group(function () {
            Route::resource('categories', 'CategoryController');
            Route::get('showsubcatgry/{mainid}/{id}', 'CategoryController@showsubcatgry')->name('categories.showsubcatgry');
            
            Route::post('categories/storesub', 'CategoryController@storesub')->name('categories.storesub');
            Route::get('createsub/{mainid}/{id}', 'CategoryController@createsub')->name('categories.createsub');
            Route::get('editsub/{mainid}/{subid}/{id}', 'CategoryController@editsub')->name('categories.editsub');
            Route::post('categories/updatesub', 'CategoryController@updatesub')->name('categories.updatesub');
            Route::get('remove-image-category', 'CategoryController@removeImage')->name('category.remove.image');
            Route::get('categories/destroysub/{mainid}/{subid}/{id}', 'CategoryController@destroysub')->name('driver.destroysub');
        });
        Route::namespace('Orders')->group(function () {
            Route::get('orders/printorder', 'OrderController@printInvoice')->name('orders.print_invoice');
            Route::resource('orders', 'OrderController');
            Route::resource('order-statuses', 'OrderStatusController');
            Route::get('orders/{id}/invoice', 'OrderController@generateInvoice')->name('orders.invoice.generate');
            Route::post('orders/print_order', 'OrderController@orderPrint')->name('orders.print_order');
        });


        //Driver
        Route::namespace('Drivers')->group(function () {
            // Route::resource('driver', 'DriverController');
            Route::get('driver/index', 'DriverController@show')->name('driver.index');
            Route::get('driver/usershow/{id}', 'DriverController@usershow')->name('driver.usershow');
            Route::get('driver/create/', 'DriverController@create')->name('driver.create');
            Route::post('driver/store', 'DriverController@store')->name('driver.store');
            Route::get('driver/edit/{id}', 'DriverController@edit')->name('driver.edit');
            Route::get('driver/destroy/{id}', 'DriverController@destroy')->name('driver.destroy');
        });

        //Payment
        Route::namespace('Payments')->group(function () {
            Route::resource('payment', 'PaymentController');
            Route::get('payment/driver/{id}/total/{total}', 'PaymentController@driverNotification');
            Route::get('payment/drivers/payment/otp', 'PaymentController@driverNotifications')->name('driver.payment.otp');
            Route::post('payment/drivers/payment', 'PaymentController@paymentSubmit')->name('driver.payment');
        });

        Route::resource('addresses', 'Addresses\AddressController');
        Route::resource('countries', 'Countries\CountryController');
        Route::resource('countries.provinces', 'Provinces\ProvinceController');
        Route::resource('countries.provinces.cities', 'Cities\CityController');
        Route::resource('couriers', 'Couriers\CourierController');
        Route::resource('attributes', 'Attributes\AttributeController');
        Route::resource('attributes.values', 'Attributes\AttributeValueController');
        Route::resource('brands', 'Brands\BrandController');

        Route::get('list-customer', 'Wallet\WalletController@index')->name('wallet.index');
        Route::get('wallet-show/{id}', 'Wallet\WalletController@walletSummery')->name('wallet.show');

        // });
        //Changed the employees to companies
        // Route::group(['middleware' => ['role:admin|superadmin, guard:employee']], function () {
        Route::resource('companies', 'CompaniesController');
        Route::get('companies/{id}/profile', 'CompaniesController@getProfile')->name('companies.profile');
        Route::get('remove-logo', 'CompaniesController@removeLogo')->name('company.remove.logo');
        Route::get('changeStatus', 'CompaniesController@changeStatus')->name('companies.status');
        Route::put('companies/{id}/profile', 'CompaniesController@updateProfile')->name('companies.profile.update');
        Route::resource('roles', 'Roles\RoleController');
        Route::resource('permissions', 'Permissions\PermissionController');
 
        Route::get('cms/tearm_condtion/index','CMS\TearmCondtionController@index')->name('cms.tearm_condtion.index');
        Route::post('cms/tearm_condtion/update', 'CMS\TearmCondtionController@update')->name('cms.tearm_condtion.update');

nilemart/resources/views/admin/dashboard.blade.php
@extends('layouts.admin.app')

@section('content')
    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="box">
            <div class="box-header with-border border-header header-color">
                <h3 class="box-title"><h2>Dashboard</h2></h3>
                @include('layouts.errors-and-messages')
            </div>
            <div class="box-body">
                @if($orders)
                    <div class="box-body">
                        <div class="box-header header-color border-header">
                            <h3>Top 5 Orders</h3>
                        </div>
                    </div>
                    <div class="box-body">
                        <div class="scroll">
                        <table class="table border-b1px" id="table-id">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Date</th>
                                    <th class="col-md-3">E-mail</th>
                                    <th >Mobile</th>
                                    <th class="col-md-2">Customer</th>
                                    <th>Total</th>
                                    <th>Status</th>
                                    <th>View</th>
                                </tr>
                            </thead>
                            <tbody>
                            @php $i=1 @endphp
                            @foreach ($orders as $order)
                                <tr>
                                    @php
                                        $wallet_amount = $order['wallet_point'] * env('DISCOUNT_POINT');
                                    @endphp
                                    @php
                                     
                                        if (isset($wallet_amount)) {
                                            $total = $order['total'] + $order['total_shipping'] + $order['tax'] - $wallet_amount;
                                        } else{
                                            $total = $order['total'] + $order['total_shipping'] + $order['tax'];
                                        }
                                    @endphp
                                    <td>{{ $i++ }}</td> 
                                    <td>{{ date('M d, Y', strtotime($order->created_at)) }}</td>
                                    <td>{{$order->email }}</td>
                                    <td>{{$order->mobile }}</td>
                                    <td>{{$order->customer_name}}</td>
                                    <td>
                                        <span class="label @if($order->total != $order->total_paid) label-danger @else label-success @endif"><i class="fa fa-rupee"></i> {{ $total }}</span>
                                    </td>
                                    <td><p class="label" style=" color: black; background-color: {{ $order->color }}">{{ ucfirst($order->status) }}</p></td>
                                    <td>
                                        <!-- <a title="Show order" href="{{ route('admin.orders.show', $order->id) }}">
                                            <p class="text-center" style="color: #fff; background-color:#00c0ef">View & Download</p>
                                        </a> -->
                                        <a title="View order" href="{{ route('admin.orders.show', $order->id) }}" class="btn btn-primary btn-sm"><i class="fa fa-eye" style="color: white; font-size:16px"></i></a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        </div>
                    </div>
                    <div class="box-body">
                        <span class="input-group-btn" style="width: 0">
                            <a href="{{ route('admin.orders.index') }}" class="btn btn-primary btn-sm"> View All</a>
                        </span>
                    </div>
                @else
                    <div class="box">
                        <div class="box-body"><p class="alert alert-warning">No orders found.</p></div>
                    </div>
                @endif
            </div>
            <div class="box-body">
                @if(!$products->isEmpty())
                    <div class="box-body">
                        <div class="box-header border-header header-color">
                            <h3>Top 5 Products</h3>
                        </div>
                    </div>
                    <div class="box-body">
                        <div class="scroll">
                        <table class="table border-b1px table-product" id="table-id">
                            <thead>
                            <tr>
                                <th class="col-md-1" >No.</th>
                                <th class="col-md-1">Name</th>
                                <th class="col-md-1">Technical</th>
                                <th class="col-md-1">Category</th>
                                <th class="col-md-1">Company</th>
                                <th class="col-md-1">Status</th>
                                <th class="col-md-1">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @php $i=1 @endphp
                            @foreach ($products as $product)
                                <tr>
                                    <td>{{ $i++ }}</td>
                                    <td>{{ $product->name }} </td>
                                    <td>{{ $product->technical_name }}</td>
                                    <td>Rs {{ $product->category }}</td>
                                    <td>Rs {{ $product->company }}</td>
                                    <td>@include('layouts.status', ['status' => $product->status])</td>
                                    <td>
                                        @php
                                           $permission = App\Helper\Permission::permission('update_stock');
                                        @endphp
                                        @if($permission->edit==1)
                                            <div class="btn-group">
                                                <a href="{{ route('admin.updateStock.edit', $product->id) }}" class="btn btn-primary btn-sm"><i class="fa fa-pencil" style="color: white; font-size:16px"></i></a>
                                            </div>
                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        </div>
                    </div>
                    <div class="box-body">
                        <span class="input-group-btn" style="width: 0">
                            <a href="{{ route('admin.updateStock.index') }}" class="btn btn-primary btn-sm"> View All</a>
                        </span>
                    </div> 
                @else
                    <div class="box">
                        <div class="box-body"><p class="alert alert-warning">No products found.</p></div>
                    </div>
                @endif
            </div>
        </div>
        <!-- /.box -->

    </section>
    <!-- /.content -->
@endsection

@section('js')
<script>
    $(document).ready(function() {
        $('#table-id').DataTable({
            "searching": false,
            "paging":   false,
            "ordering": false,
            "info":     false
        });
        $('.table-product').DataTable({
            "searching": false,
            "paging":   false,
            "ordering": false,
            "info":     false
        });
    } );
</script>
@endsection