nilemart/routes/web.php
            Route::resource('offers', 'OffersController');
            Route::get('offers_product', 'OffersController@getProduct')->name('offers.product.attr');
            Route::post('offers/{id}', 'OffersController@update')->name('offers.update');
            Route::get('remove-image-offer', 'OffersController@removeImage')->name('offers.remove.image');
        });
        Route::namespace('Categories')->group(function () {
            Route::resource('categories', 'CategoryController');
            Route::get('showsubcatgry/{mainid}/{id}', 'CategoryController@showsubcatgry')->name('categories.showsubcatgry');
            
            Route::post('categories/storesub', 'CategoryController@storesub')->name('categories.storesub');
            Route::get('createsub/{mainid}/{id}', 'CategoryController@createsub')->name('categories.createsub');
            Route::get('editsub/{mainid}/{subid}/{id}', 'CategoryController@editsub')->name('categories.editsub');
            Route::post('categories/updatesub', 'CategoryController@updatesub')->name('categories.updatesub');
            Route::get('remove-image-category', 'CategoryController@removeImage')->name('category.remove.image');
            Route::get('categories/destroysub/{mainid}/{subid}/{id}', 'CategoryController@destroysub')->name('driver.destroysub');
        });
        Route::namespace('Orders')->group(function () {
            Route::get('orders/printorder', 'OrderController@printInvoice')->name('orders.print_invoice');
            Route::resource('orders', 'OrderController');
            Route::resource('order-statuses', 'OrderStatusController');
            Route::get('orders/{id}/invoice', 'OrderController@generateInvoice')->name('orders.invoice.generate');
            Route::post('orders/print_order', 'OrderController@orderPrint')->name('orders.print_order');
        });


        //Driver
        Route::namespace('Drivers')->group(function () {
            // Route::resource('driver', 'DriverController');
            Route::get('driver/index', 'DriverController@show')->name('driver.index');
            Route::get('driver/usershow/{id}', 'DriverController@usershow')->name('driver.usershow');
            Route::get('driver/create/', 'DriverController@create')->name('driver.create');
            Route::post('driver/store', 'DriverController@store')->name('driver.store');
            Route::get('driver/edit/{id}', 'DriverController@edit')->name('driver.edit');
            Route::get('driver/destroy/{id}', 'DriverController@destroy')->name('driver.destroy');
        });

        //Payment
        Route::namespace('Payments')->group(function () {
            Route::resource('payment', 'PaymentController');
            Route::get('payment/driver/{id}/total/{total}', 'PaymentController@driverNotification');
            Route::get('payment/drivers/payment/otp', 'PaymentController@driverNotifications')->name('driver.payment.otp');
            Route::post('payment/drivers/payment', 'PaymentController@paymentSubmit')->name('driver.payment');
        });

        Route::resource('addresses', 'Addresses\AddressController');
        Route::resource('countries', 'Countries\CountryController');
        Route::resource('countries.provinces', 'Provinces\ProvinceController');
        Route::resource('countries.provinces.cities', 'Cities\CityController');
        Route::resource('couriers', 'Couriers\CourierController');
        Route::resource('attributes', 'Attributes\AttributeController');
        Route::resource('attributes.values', 'Attributes\AttributeValueController');
        Route::resource('brands', 'Brands\BrandController');

        Route::get('list-customer', 'Wallet\WalletController@index')->name('wallet.index');
        Route::get('wallet-show/{id}', 'Wallet\WalletController@walletSummery')->name('wallet.show');

        // });
        //Changed the employees to companies
        // Route::group(['middleware' => ['role:admin|superadmin, guard:employee']], function () {
        Route::resource('companies', 'CompaniesController');
        Route::get('companies/{id}/profile', 'CompaniesController@getProfile')->name('companies.profile');
        Route::get('remove-logo', 'CompaniesController@removeLogo')->name('company.remove.logo');
        Route::get('changeStatus', 'CompaniesController@changeStatus')->name('companies.status');
        Route::put('companies/{id}/profile', 'CompaniesController@updateProfile')->name('companies.profile.update');
        Route::resource('roles', 'Roles\RoleController');
        Route::resource('permissions', 'Permissions\PermissionController');
 
        Route::get('cms/tearm_condtion/index','CMS\TearmCondtionController@index')->name('cms.tearm_condtion.index');
        Route::post('cms/tearm_condtion/update', 'CMS\TearmCondtionController@update')->name('cms.tearm_condtion.update');

        Route::get('cms/privacy_policy/index','CMS\PrivacyPolicyController@index')->name('cms.privacy_policy.index');
        Route::post('cms/privacy_policy/update', 'CMS\PrivacyPolicyController@update')->name('cms.privacy_policy.update');
        // });

        //Faq
        Route::get('faq/index', 'Faq\FaqController@index')->name('faq.index');
        Route::get('faq/create/', 'Faq\FaqController@create')->name('faq.create');
        Route::post('faq/store', 'Faq\FaqController@store')->name('faq.store');
        Route::get('faq/edit/{id}', 'Faq\FaqController@edit')->name('faq.edit');
        Route::get('faq/destroy/{id}', 'Faq\FaqController@destroy')->name('faq.destroy');
        // });


        Route::namespace('Orderpurchase')->group(function () {
            Route::resource('orderpurchase', 'OrderpurchaseController');
            Route::post('removeProductattribute','OrderpurchaseController@removeProductattribute')->name('orderpurchase.removeProductattribute');
            Route::get('getProducts', 'OrderpurchaseController@getProducts')->name('orderpurchase.getProducts');
            Route::post('getProductsattribute', 'OrderpurchaseController@getProductsattribute')->name('orderpurchase.getProductsattribute');
            Route::post('getProductsdetail', 'OrderpurchaseController@getProductsdetail')->name('orderpurchase.getProductsdetail');
            Route::post('orderpurchase/update/{id}', 'OrderpurchaseController@update')->name('orderpurchase.update');
            Route::get('orderpurchase/{id}/invoice', 'OrderpurchaseController@generateInvoice')->name('orderpurchase.invoice.generate');
        });
    });
    Route::get('translate', 'Admin\TranslateController@translate')->name('translate');
});

/**
 * Frontend routes
 */
Auth::routes();
Route::namespace('Auth')->group(function () {
    Route::get('cart/login', 'CartLoginController@showLoginForm')->name('cart.login');
    Route::post('cart/login', 'CartLoginController@login')->name('cart.login');
    Route::get('logout', 'LoginController@destroy');
    Route::get('user/login', 'LoginController@loginform')->name('userLogin');
    Route::post('/user/login', 'LoginController@loginstore')->name('loginstore');
    Route::post('/user/register/login', 'LoginController@registerloginstore')->name('registerloginstore');
    Route::post('/register/{no}', 'LoginController@register')->name('userRegistration');
    Route::post('register', 'LoginController@store')->name('userStorRegistration');
    Route::post('resendotp', 'LoginController@resendOtp')->name('resendotp');

});

Route::namespace('Front')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::group(['middleware' => ['auth', 'web']], function () {

        Route::namespace('Payments')->group(function () {
            Route::get('bank-transfer', 'BankTransferController@index')->name('bank-transfer.index');
            Route::post('bank-transfer', 'BankTransferController@store')->name('bank-transfer.store');
        });

        Route::namespace('Addresses')->group(function () {
            Route::resource('country.state', 'CountryStateController');
            Route::resource('state.city', 'StateCityController');
        });

        Route::get('accounts', 'AccountsController@index')->name('accounts');
        Route::get('checkout', 'CheckoutController@index')->name('checkout.index');
        Route::post('checkout', 'CheckoutController@store')->name('checkout.store');
        Route::get('checkout/execute', 'CheckoutController@executePayPalPayment')->name('checkout.execute');
        Route::post('checkout/execute', 'CheckoutController@charge')->name('checkout.execute');
        Route::get('checkout/cancel', 'CheckoutController@cancel')->name('checkout.cancel');
        Route::get('checkout/success', 'CheckoutController@success')->name('checkout.success');
        Route::resource('customer.address', 'CustomerAddressController');
    });
    Route::resource('cart', 'CartController');
    Route::get("category/{slug}", 'CategoryController@getCategory')->name('front.category.slug');
    // Route::get("search", 'ProductController@search')->name('search.product');
    // Route::get("{product}", 'ProductController@show')->name('front.get.product');

    Route::get("productCategory", 'ProductController@productCategory')->name('productCategory.product');
    Route::get("productSubCategory/{id}", 'ProductController@productSubCategory')->name('productSubCategory.product');
    Route::get("productDetail/{id}", 'ProductController@productDetail')->name('productDetail.product');
    Route::get("productListing", 'ProductController@productListing')->name('productListing.product');
    Route::get("product/{id}", 'ProductController@productCategoryListing')->name('productCategoryListing.product');
    Route::get("productCategory/{cat}", 'ProductController@productCategoryListingCat')->name('productCategoryListingCat.product');
    Route::get("productSubSubCategory/{id}", 'ProductController@productSubSubCategory')->name('productSubSubCategory.name');
    

nilemart/app/Http/Controllers/Admin/Couriers/CourierController.php
<?php

namespace App\Http\Controllers\Admin\Couriers;

use App\Shop\Couriers\Repositories\CourierRepository;
use App\Shop\Couriers\Repositories\Interfaces\CourierRepositoryInterface;
use App\Shop\Couriers\Requests\CreateCourierRequest;
use App\Shop\Couriers\Requests\UpdateCourierRequest;
use App\Http\Controllers\Controller;

class CourierController extends Controller
{
    /**
     * @var CourierRepositoryInterface
     */
    private $courierRepo;

    /**
     * CourierController constructor.
     * @param CourierRepositoryInterface $courierRepository
     */
    public function __construct(CourierRepositoryInterface $courierRepository)
    {
        $this->courierRepo = $courierRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.couriers.list', ['couriers' => $this->courierRepo->listCouriers('name', 'asc')]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.couriers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  CreateCourierRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateCourierRequest $request)
    {
        $this->courierRepo->createCourier($request->all());

        $request->session()->flash('message', 'Create successful');
        return redirect()->route('admin.couriers.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(int $id)
    {
        return view('admin.couriers.edit', ['courier' => $this->courierRepo->findCourierById($id)]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  UpdateCourierRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCourierRequest $request, $id)
    {
        $courier = $this->courierRepo->findCourierById($id);

        $update = new CourierRepository($courier);
        $update->updateCourier($request->all());

        $request->session()->flash('message', 'Update successful');
        return redirect()->route('admin.couriers.edit', $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(int $id)
    {
        $courier = $this->courierRepo->findCourierById($id);

        $courierRepo = new CourierRepository($courier);
        $courierRepo->delete();

        request()->session()->flash('message', 'Delete successful');
        return redirect()->route('admin.couriers.index');
    }
}

nilemart/resources/views/admin/couriers/create.blade.php
@extends('layouts.admin.app')

@section('content')
    <!-- Main content -->
    <section class="content">
        @include('layouts.errors-and-messages')
        <div class="box">
            <form action="{{ route('admin.couriers.store') }}" method="post" class="form">
                <div class="box-body">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label for="name">Name <span class="text-danger">*</span></label>
                        <input type="text" name="name" id="name" placeholder="Name" class="form-control" value="{{ old('name') }}">
                    </div>
                    <div class="form-group">
                        <label for="description">Description </label>
                        <textarea name="description" id="description" rows="5" class="form-control" placeholder="Description">{{ old('description') }}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="URL">URL</label>
                        <div class="input-group">
                            <span class="input-group-addon">http://</span>
                            <input type="text" name="url" id="url" placeholder="Link" class="form-control" value="{{ old('url') }}">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="is_free">Is Free Delivery? </label>
                        <select name="is_free" id="is_free" class="form-control">
                            <option value="0">No</option>
                            <option value="1" selected="selected">Yes</option>
                        </select>
                    </div>
                    <div class="form-group" style="display: none" id="delivery_cost">
                        <label for="cost">Delivery Cost <span class="text-danger">*</span></label>
                        <div class="input-group">
                            <span class="input-group-addon">{{config('cart.currency')}}</span>
                            <input class="form-control" type="text" id="cost" name="cost" placeholder="{{config('cart.currency')}}" value="{{old('cost')}}">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="status">Status </label>
                        <select name="status" id="status" class="form-control">
                            <option value="0">Disable</option>
                            <option value="1">Enable</option>
                        </select>
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <div class="btn-group">
                        <a href="{{ route('admin.products.index') }}" class="btn btn-default">Back</a>
                        <button type="submit" class="btn btn-primary">Create</button>
                    </div>
                </div>
            </form>
        </div>
        <!-- /.box -->

    </section>
    <!-- /.content -->
@endsection

nilemart/resources/views/admin/couriers/edit.blade.php
@extends('layouts.admin.app')

@section('content')
    <!-- Main content -->
    <section class="content">
        @include('layouts.errors-and-messages')
        <div class="box">
            <form action="{{ route('admin.couriers.update', $courier->id) }}" method="post" class="form">
                <div class="box-body">
                    {{ csrf_field() }}
                    <input type="hidden" name="_method" value="put">
                    <div class="form-group">
                        <label for="name">Name <span class="text-danger">*</span></label>
                        <input type="text" name="name" id="name" placeholder="Name" class="form-control" value="{{ $courier->name ?: old('name') }}">
                    </div>
                    <div class="form-group">
                        <label for="description">Description </label>
                        <textarea name="description" id="description" rows="5" class="form-control" placeholder="Description">{{ $courier->description ?: old('description') }}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="URL">URL</label>
                        <div class="input-group">
                            <span class="input-group-addon">http://</span>
                            <input type="text" name="url" id="url" placeholder="Link" class="form-control" value="{{ $courier->url ?: old('url') }}">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="is_free">Free Delivery? </label>
                        <select name="is_free" id="is_free" class="form-control">
                            <option value="0" @if($courier->is_free == 0) selected="selected" @endif>No</option>
                            <option value="1" @if($courier->is_free == 1) selected="selected" @endif>Yes</option>
                        </select>
                    </div>
                    <div class="form-group" @if($courier->is_free == 1) style="display: none" @endif id="delivery_cost">
                        <label for="cost">Delivery Cost <span class="text-danger">*</span></label>
                        <div class="input-group">
                            <span class="input-group-addon">{{config('cart.currency')}}</span>
                            <input class="form-control" type="text" id="cost" name="cost" placeholder="{{config('cart.currency')}}" value="{{$courier->cost}}">
                        </div>
                    </div>
                    <div class="form-group">
                        @include('admin.shared.status-select', ['status' => $courier->status])
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <div class="btn-group">
                        <a href="{{ route('admin.couriers.index') }}" class="btn btn-default">Back</a>
                        <button type="submit" class="btn btn-primary">Update</button>
                    </div>
                </div>
            </form>
        </div>
        <!-- /.box -->

    </section>
    <!-- /.content -->
@endsection

nilemart/resources/views/admin/couriers/list.blade.php
@extends('layouts.admin.app')

@section('content')
    <!-- Main content -->
    <section class="content">

    @include('layouts.errors-and-messages')
    <!-- Default box -->
        @if($couriers)
            <div class="box">
                <div class="box-body">
                    <h2> <i class="fa fa-truck"></i> Couriers</h2>
                    <table class="table">
                        <thead>
                            <tr>
                                <td class="col-md-2">Name</td>
                                <td class="col-md-2">Description</td>
                                <td class="col-md-2">URL</td>
                                <td class="col-md-1">Is Free?</td>
                                <td class="col-md-1">Cost</td>
                                <td class="col-md-1">Status</td>
                                <td class="col-md-3">Actions</td>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach ($couriers as $courier)
                            <tr>
                                <td>{{ $courier->name }}</td>
                                <td>{{ str_limit($courier->description, 100, ' ...') }}</td>
                                <td>{{ $courier->url }}</td>
                                <td>
                                    @include('layouts.status', ['status' => $courier->is_free])
                                </td>
                                <td>
                                    {{config('cart.currency')}} {{ $courier->cost }}
                                </td>
                                <td>@include('layouts.status', ['status' => $courier->status])</td>
                                <td>
                                    <form action="{{ route('admin.couriers.destroy', $courier->id) }}" method="post" class="form-horizontal">
                                        {{ csrf_field() }}
                                        <input type="hidden" name="_method" value="delete">
                                        <div class="btn-group">
                                            <a href="{{ route('admin.couriers.edit', $courier->id) }}" class="btn btn-primary btn-sm"><i class="fa fa-edit"></i> Edit</a>
                                            <button onclick="return confirm('Are you sure?')" type="submit" class="btn btn-danger btn-sm"><i class="fa fa-times"></i> Delete</button>
                                        </div>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        @endif

    </section>
    <!-- /.content -->
@endsection